// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20220401170609_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Adopted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Adopted = false,
                            Age = 21,
                            Name = "Lola",
                            Sex = "Female",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Adopted = true,
                            Age = 17,
                            Name = "Steve",
                            Sex = "Male",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Adopted = false,
                            Age = 15,
                            Name = "Reggie",
                            Sex = "Male",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Adopted = true,
                            Age = 13,
                            Name = "Silver",
                            Sex = "Male",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Adopted = false,
                            Age = 3,
                            Name = "Goldie",
                            Sex = "Female",
                            Species = "Bird"
                        },
                        new
                        {
                            AnimalId = 6,
                            Adopted = false,
                            Age = 1,
                            Name = "Prince",
                            Sex = "Male",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Adopted = true,
                            Age = 1,
                            Name = "Alf",
                            Sex = "Female",
                            Species = "Mouse"
                        },
                        new
                        {
                            AnimalId = 8,
                            Adopted = true,
                            Age = 5,
                            Name = "Sam",
                            Sex = "Male",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 9,
                            Adopted = false,
                            Age = 4,
                            Name = "Teenager",
                            Sex = "Male",
                            Species = "Bird"
                        },
                        new
                        {
                            AnimalId = 10,
                            Adopted = true,
                            Age = 28,
                            Name = "Cranston",
                            Sex = "TG",
                            Species = "Human"
                        },
                        new
                        {
                            AnimalId = 11,
                            Adopted = false,
                            Age = 77,
                            Name = "Snoop",
                            Sex = "Female",
                            Species = "Turtle"
                        },
                        new
                        {
                            AnimalId = 12,
                            Adopted = false,
                            Age = 10,
                            Name = "Klingon",
                            Sex = "Male",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 13,
                            Adopted = true,
                            Age = 999,
                            Name = "Trenton",
                            Sex = "TG",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
